tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "wez/wezterm"
brew "ack"
brew "aria2"
brew "asciinema"
brew "awscli"
brew "python@3.9"
brew "composer"
brew "ctags"
brew "fd"
brew "ffmpeg"
brew "gh"
brew "git"
brew "git-delta"
brew "gnupg"
brew "graphviz"
brew "htop"
brew "hub"
brew "hugo"
brew "inetutils"
brew "jq"
brew "kubernetes-cli"
brew "lazygit"
brew "mas"
brew "minikube"
brew "mitmproxy"
brew "mosh"
brew "neofetch"
brew "neovim", args: ["HEAD"]
brew "node"
brew "onefetch"
brew "openconnect"
brew "p7zip"
brew "pinentry-mac"
brew "protoc-gen-go"
brew "pv"
brew "ripgrep"
brew "spotify-tui"
brew "tmux"
brew "wget"
brew "wtfutil"
brew "yt-dlp"
brew "zsh"
cask "1password"
cask "1password-cli"
cask "cleanmymac"
cask "coconutbattery"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-hack-nerd-font"
cask "github"
cask "google-chrome"
cask "maccy"
cask "microsoft-edge"
cask "mos"
cask "numi"
cask "obsidian"
cask "oversight"
cask "paw"
cask "rectangle"
cask "slack"
cask "spotify"
cask "stretchly"
cask "sublime-text"
cask "tableplus"
cask "telegram"
cask "tunnelblick"
cask "visual-studio-code"
cask "vlc"
cask "wezterm"
cask "zoom"
mas "Bear", id: 1091189122
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Reeder", id: 1529448980
mas "The Unarchiver", id: 425424353
mas "Toggl Track", id: 1291898086
